import gradio as gr
import os
import re
import base64
from databricks.sdk import WorkspaceClient

# ── Constants ─────────────────────────────────────────────────────────────────
SUPERVISOR_ENDPOINT = "mas-8821e19b-endpoint"
AVAILABLE_SHOWS = [
    "Sunday Football", "Crime Files", "Heartland Hospital", "The Baking Hour",
    "Quiz Champions", "Night Detectives", "Coast Guard Rescue", "Startup Stories",
    "Late Night Laughs", "Morning Brew", "Weekend Wrap", "Family Feud Live",
]

# ── Image Handling ────────────────────────────────────────────────────────────
def get_base64_encoded_image(image_path):
    try:
        with open(image_path, "rb") as img_file:
            return base64.b64encode(img_file.read()).decode("utf-8")
    except Exception: return ""

logo_light_base64 = get_base64_encoded_image("VSNT_BIG.png")
logo_dark_base64 = get_base64_encoded_image("VSNT_BIG.D.png")

# ── Core Logic & Simplified Formatting ────────────────────────────────────────

def format_as_press_release(raw_text: str, show_name: str) -> str:
    # 1. Clean the agent noise
    marker = "FOR IMMEDIATE RELEASE"
    content = raw_text
    if marker in raw_text:
        content = marker + raw_text.split(marker)[-1]
    
    content = re.sub(r'<name>.*?</name>', '', content)
    content = re.sub(r'\[\^.*?\]', '', content).strip()

    # 2. Simplified HTML Structure for perfect alignment
    return f"""
    <div style="font-family: Arial, sans-serif; max-width: 100%; margin: 0 auto; padding: 30px; 
                border: 1px solid var(--border-color-primary); border-radius: 8px; background: var(--background-fill-secondary);">

        <div style="background: #1a1a2e; color: white; padding: 15px 20px; border-radius: 6px; margin-bottom: 24px;">
            <h2 style="margin:0; font-size: 24px; color: white !important;">PRESS RELEASE</h2>
            <p style="margin:6px 0 0; color:#aaa !important; font-size: 14px;">
                {show_name} &nbsp;|&nbsp; FOX &nbsp;|&nbsp; Week 20
            </p>
        </div>

        <div style="line-height:1.8; color: var(--body-text-color); white-space: pre-wrap; text-align: left; font-size: 1.05rem;">{content}</div>

        <hr style="margin-top:30px; border:none; border-top:1px solid var(--border-color-primary); opacity: 0.3;">
        <p style="color: var(--body-text-color); opacity: 0.5; font-size:12px;">
            Generated by Press Release Generator Demo &nbsp;|&nbsp; Source: main.genie_demo
        </p>
    </div>
    """

def generate_press_release(show_name: str) -> tuple[str, str]:
    if not show_name: return "", "Select a show."
    try:
        w = WorkspaceClient()
        payload = {"input": [{"role": "user", "content": f"Generate a professional press release for '{show_name}'."}]}
        endpoint_path = f"/serving-endpoints/{SUPERVISOR_ENDPOINT}/invocations"
        raw_response = w.api_client.do("POST", endpoint_path, body=payload)
        
        extracted_text = []
        if "output" in raw_response:
            for output_item in raw_response["output"]:
                for content_item in output_item.get("content", []):
                    text = content_item.get("text", "")
                    if text: extracted_text.append(text)
        
        raw_output = " ".join(extracted_text)
        return format_as_press_release(raw_output, show_name), "Generated successfully."
    except Exception as e:
        return "", f"Error: {str(e)}"

# ── UI Layout ──────────────────────────────────────────────────────────────────

CSS = """
#masthead { display: flex; align-items: center; border-bottom: 1px solid var(--border-color-primary); padding: 20px 0; margin-bottom: 24px; gap: 25px; }
#versant-logo { flex: 0 0 180px; }
#versant-logo img { width: 100%; height: auto; }

#logo-dark { display: none; }
@media (prefers-color-scheme: dark) { #logo-light { display: none; } #logo-dark { display: block; } }

#input-panel { background: var(--block-background-fill); border: 1px solid var(--border-color-primary); border-radius: 8px; padding: 16px; }
.gradio-container label span { background: #6366f1 !important; color: white !important; border-radius: 4px; padding: 2px 8px; }
"""

def build_ui() -> gr.Blocks:
    with gr.Blocks(css=CSS, theme=gr.themes.Soft()) as app:
        gr.HTML(f"""
            <div id="masthead">
                <div id="versant-logo">
                    <img id="logo-light" src="data:image/png;base64,{logo_light_base64}" />
                    <img id="logo-dark" src="data:image/png;base64,{logo_dark_base64}" />
                </div>
                <div id="masthead-text">
                    <h1 style="margin:0; font-size: 2.2rem;">Press Release Generator</h1>
                    <p style="margin:0; opacity:0.8;">Versant Innovation Pod &nbsp;·&nbsp; Databricks Supervisor</p>
                </div>
            </div>
        """)
        
        with gr.Row():
            with gr.Column(scale=1, elem_id="input-panel"):
                gr.Markdown("### Configuration")
                show_input = gr.Dropdown(choices=AVAILABLE_SHOWS, label="Select Show", value="Sunday Football")
                generate_btn = gr.Button("Generate Press Release", variant="primary")
                status = gr.Textbox(label="Status", interactive=False)
                
                with gr.Accordion("System Details", open=False):
                    gr.Markdown("""
                    **Technical Stack:** [cite: 5, 6]
                    * **Data:** Fetches real-time metrics via Genie (SQL Warehouse) 
                    * **Style:** Formats content via Knowledge Assistant (RAG) [cite: 7, 24]
                    * **Inference:** Llama 3.3 70B [cite: 10, 39]
                    """)
            
            with gr.Column(scale=2):
                output = gr.HTML(label="Final Press Release Draft")

        generate_btn.click(fn=generate_press_release, inputs=[show_input], outputs=[output, status])
    return app

if __name__ == "__main__":
    app = build_ui()
    app.launch(server_name="0.0.0.0", server_port=int(os.getenv("GRADIO_SERVER_PORT", 7860)))
